apiVersion: v1
kind: Service
metadata:
  name: suspicious-events-detector-service
spec:
  type: NodePort
  selector:
    app: suspicious-events-detector-app
  ports:
  - protocol: TCP
    nodePort: 30301
    port: 8080
    targetPort: 8080